version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    volumes:
      - ./client:/app
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        npx prisma migrate dev --name init &&
        npx prisma generate &&
        npm run dev
      "

  ws:
    build:
      context: ./ws
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./ws:/app
    environment:
      - NODE_ENV=development

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
